### ISSUE TITLE
java.io.IOException: error=2, No such file or directory

### ISSUE THREAD

**Issue by phamduythai92mta** [bastienjalbert/topguw#10]
when i run command get possible keystreams i got this error and the files ...SI_BURSTS_NO_TA and ...POSSIBLE_SEYSTREANs and ...ENCRYPTED_SI_POS are empty
can you help me fix this error?? thanks!

**Comment by bastienjalbert** [comment]
Make sure you have as clear a record as possible (cfile). Also from memory there can be problems with frequency hopping with the rtl-sdr.
