### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by ijarraki** [bastienjalbert/topguw#4]
I appreciate your effort in this matter, yet I find it incumbent upon me to suggest that you make this software compatible with gr-gsm (on GitHub) instead of legacy airprobe.

Legacy airprobe has a whole host of issues and is outdated. Gr-gsm is being actively developed by one of the original airprobe devs, is GR3.7 compatible, has an integrated cfile output option and can now output verbose frames (to be decoded with gsmframedecoder).

**Comment by bastienjalbert** [comment]
Yes, I had think about few weeks ago. Gr-gsm is, without a doubt, better and like you said under development right now. 

Sadly I don't have any time to work on Topguw now, but it will be one of the most important thing that I will try to do when I'll be back on Topguw.

Thank you for the advise.
