### ISSUE TITLE
why when capture a gsm signal,i Extract SI Plaintext version it is empty?????

### ISSUE THREAD

**Issue by stackprogramer** [bastienjalbert/topguw#7]
hi,why when capture a gsm signal,i Extract SI Plaintext version it is empty?????
i uses gr-gsm,gnuradio3.7
why the output file Extract SI Plaintext version is empty!!!??????
thanks

**Comment by bastienjalbert** [comment]
https://github.com/bastienjalbert/topguw#how-to-install
Dependencies, gnuradio 3.6.... Start by this.
