### ISSUE TITLE
how i can   Sorry, don't find any Immediate Assignment on this cfile.

### ISSUE THREAD

**Issue by stackprogramer** [bastienjalbert/topguw#8]
hi, i installed topguw,i capture gsm900, it convert to cfile but after this:

> Topguw> Configuration has successfuly changed.
> Topguw> Getting channel outputs for the cfile, please wait...
> Topguw> An error occur when trying to clean the output for dedicated chanel : 
> Topguw> Sorry, don't find any Immediate Assignment on this cfile.
> Topguw> Please choose an other file, or sniff again a GSM tower.
> Topguw> Making dirty cleaner, please wait...
> Topguw> Files correctly loaded.

what means, how can i solve it???

**Comment by bastienjalbert** [comment]
**_Sorry, don't find any Immediate Assignment on this cfile._**
I think it is pretty much clear, you have not any Immediate Assignment frame on your recorded data...
